### ISSUE TITLE
Component does not work on V23

### ISSUE THREAD

**Issue by paodb** [vaadin-component-factory/vcf-popup#11]
Trying to use version 3.0.0 in an application running on Vaadin 23.0.0.alpha3 breaks the application.
Console log shows this error:

```
Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-lumo-styles" has already been used with this registry
    at eval (webpack-internal:///../node_modules/@vaadin-component-factory/vcf-popup/node_modules/@vaadin/vaadin-lumo-styles/version.js:14:16)
    at Module.../node_modules/@vaadin-component-factory/vcf-popup/node_modules/@vaadin/vaadin-lumo-styles/version.js (http://localhost:8080/VAADIN/build/vaadin-0-7c136ee2437530b7cda2.cache.js:215:1)
    at __webpack_require__ (http://localhost:8080/VAADIN/build/vaadin-bundle-d5048dc2ff0c0308c95a.cache.js:64:30)
    at eval (webpack-internal:///../node_modules/@vaadin-component-factory/vcf-popup/node_modules/@vaadin/vaadin-lumo-styles/spacing.js:3:69)
    at Module.../node_modules/@vaadin-component-factory/vcf-popup/node_modules/@vaadin/vaadin-lumo-styles/spacing.js (http://localhost:8080/VAADIN/build/vaadin-0-7c136ee2437530b7cda2.cache.js:179:1)
    at __webpack_require__ (http://localhost:8080/VAADIN/build/vaadin-bundle-d5048dc2ff0c0308c95a.cache.js:64:30)
    at eval (webpack-internal:///../node_modules/@vaadin-component-factory/vcf-popup/theme/lumo/vcf-popup-styles.js:2:92)
    at Module.../node_modules/@vaadin-component-factory/vcf-popup/theme/lumo/vcf-popup-styles.js (http://localhost:8080/VAADIN/build/vaadin-0-7c136ee2437530b7cda2.cache.js:323:1)
    at __webpack_require__ (http://localhost:8080/VAADIN/build/vaadin-bundle-d5048dc2ff0c0308c95a.cache.js:64:30)
    at eval (webpack-internal:///../node_modules/@vaadin-component-factory/vcf-popup/theme/lumo/vcf-popup.js:2:75)
```

This error also makes other add-ons using popup as a dependency not to work either, for example: Enhanced Grid.

**Comment by paodb** [comment]
Updating npm version to 8.3 fixes the issue and the component works okay in a Vaadin 23 application.
